name = "CamiMath"
uuid = "d302b3f7-c8ae-418d-9fc2-2c0a42bddda0"
authors = ["Jook Walraven <69215586+walra356@users.noreply.github.com> and contributors"]
version = "0.1.24"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"

[compat]
Documenter = "1.14"
DocumenterInterLinks = "1.1"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
